import { verticalScale, scale, ScaledSheet, moderateScale, moderateVerticalScale } from "react-native-size-matters";

const styles = ScaledSheet.create({
    container:{
        flex:1,
        width:"100%",
        height:"100%",
        padding:10,
    },
    titleContainer:{
        fontSize:moderateScale(16),
        marginBottom:44,
        color:"black",
    },
    box:{
        borderWidth:1,
        padding:18,
        marginBottom:25,
    },
    titleBox:{
        fontSize:moderateScale(25),
        marginBottom:30,
        color:"black",
        fontWeight:"800",
    },
    line:{
        display:"flex",
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center",
        height:moderateScale(30),
        marginBottom:11,
    },
    titleLine:{
        fontSize:moderateScale(20),
        color:"black",
        fontWeight:"600",
    },
    link:{
        display:"flex",
        flexDirection:"row",
        alignItems:"center",
    },
    textLink:{
        fontSize:moderateScale(10),
        color:"black",
    },
    iconLinkView:{
        width:moderateScale(22),
        height:moderateScale(22),
    },
    iconLink:{
        width:moderateScale(22),
        height:moderateScale(22),
        resizeMode:"contain",
        marginLeft:5,
    },
    iconLinkView:{
        display:"flex",
        flexDirection:"row",
    },
    editionButton:{
        width:moderateScale(200),
        height:moderateScale(75),
        justifyContent:"center",
        alignItems:"center",
        backgroundColor:"#8429AE",
        borderRadius:15,
        borderWidth:2,
    },
    textButton:{
        fontSize:moderateScale(25),
        fontWeight:"900",
        color:"#ffffff",
    },
    buttonBox:{
        width:"100%",
        alignItems:"center",
        marginBottom:25,
    },
    textLink:{
        fontSize: moderateVerticalScale(12),
    }
})

export default styles;