import {StyleSheet} from "react-native";

const styles = StyleSheet.create({
    container:{
        flex:1,
        height:"100%",
        paddingTop:10,
        paddingRight:10,
        paddingLeft:10,
        width:"100%",
        
    },
    textOutBox:{
        fontSize:16,
        marginBottom:20,
    },
    box1:{
        width:"100%",
        height:250,
        padding:10,
        borderWidth:2,
        marginVertical:10,
    },
    content:{
        width:"100%",
        height:50,
        flexDirection:"row",
        justifyContent:"space-between",
        marginVertical:5,
        alignItems:"center",
    },
    boxImageWithText:{
        width:90,
        height:25,
        flexDirection:"row",
        justifyContent:"space-around",
        alignItems:"center",
    },
    boxImage:{
        width:30,
        height:25,
    },
    boxImageWith2Image:{
        width:55,
        height:25,
        flexDirection:"row",
        justifyContent:"space-around",
        justifyContent:"space-around",
        alignItems:"center",
    },
    boxImageWith3Image:{
        width:80,
        height:25,
        flexDirection:"row",
        justifyContent:"space-around",
        justifyContent:"space-around",
        alignItems:"center",
    },
    boxImageWithTextAndress1:{
        width:230,
        height:25,
        flexDirection:"row",
        justifyContent:"space-around",
        alignItems:"center",
    },boxImageWithTextAndress2:{
        width:180,
        height:25,
        flexDirection:"row",
        justifyContent:"space-around",
        alignItems:"center",
    },
    boxImageWithTextPassword:{
        width:90,
        height:25,
        flexDirection:"row",
        justifyContent:"space-around",
        alignItems:"center",
    },
    boxImageWithTextUsername:{
        width:130,
        height:25,
        flexDirection:"row",
        justifyContent:"space-around",
        alignItems:"center",
    },
    image:{
        height:25,
        width:25,
        resizeMode:"contain",
    },
    textContent:{
        fontSize:20,
        color:"#000000",

    },
    titleBox:{
        fontSize:25,
        color:"#000000",
        fontWeight:"700",
    },
    editionButtonContainer:{
        width:"100%",
        height:100,
        justifyContent:"center",
        alignItems:"center",
    },
    editionButton:{
        width:200,
        height:"80%",
        justifyContent:"center",
        alignItems:"center",
        backgroundColor:"#8429AE",
        borderRadius:15,
        borderWidth:2,
    },
    textButton:{
        fontSize:25,
        fontWeight:"900",
        color:"#000000",
    }
})

export default styles;