import {StyleSheet} from "react-native";
import { ScaledSheet, scale, moderateScale, verticalScale, moderateVerticalScale, moderateHorizontalScale } from "react-native-size-matters";

const styles = ScaledSheet.create({
    container:{
        flex:1,
        width:"100%",
        height:"100%",
        padding:10,
        
    },
    textOutBox:{
        fontSize:scale(16),
        marginBottom:20,
    },
    box:{
        width:"100%",
        height:moderateVerticalScale(410),
        padding:10,
        borderWidth:2,
    },
    content:{
        width:"100%",
        height:moderateVerticalScale(50),
        flexDirection:"row",
        justifyContent:"space-between",
        marginVertical:5,
        alignItems:"center",
    },
    boxImageWithText:{
        width:scale(90),
        height:scale(25),
        flexDirection:"row",
        alignItems:"center",
        justifyContent:"flex-end"
    },
    boxImage:{
        width:scale(30),
        height:scale(25),
    },
    boxImageWith2Image:{
        width:scale(55),
        height:scale(25),
        flexDirection:"row",
        justifyContent:"flex-end",
        alignItems:"center",
    },
    boxImageWith3Image:{
        width:scale(80),
        height:scale(25),
        flexDirection:"row",
        justifyContent:"flex-end",
        alignItems:"center",
    },
    boxImageWithTextEmail:{
        width:scale(200),
        height:scale(25),
        flexDirection:"row",
        justifyContent:"flex-end",
        alignItems:"center",
    },
    boxImageWithTextPassword:{
        width:scale(90),
        height:scale(25),
        flexDirection:"row",
        justifyContent:"flex-end",
        alignItems:"center",
    },
    boxImageWithTextUsername:{
        width:scale(130),
        height:scale(25),
        flexDirection:"row",
        justifyContent:"flex-end",
        alignItems:"center",
    },
    image:{
        height:moderateVerticalScale(25),
        width:moderateScale(25),
        resizeMode:"contain",
        
    },
    textContent:{
        fontSize:scale(16),
        color:"#000000",

    },
    titleBox:{
        fontSize:scale(20),
        color:"#000000",
    },
    editionButtonContainer:{
        width:"100%",
        height:moderateVerticalScale(100),
        justifyContent:"center",
        alignItems:"center",
    },
    editionButton:{
        width:scale(200),
        height:"80%",
        justifyContent:"center",
        alignItems:"center",
        backgroundColor:"#8429AE",
        borderRadius:15,
        borderWidth:2,
    },
    textButton:{
        fontSize:scale(25),
        fontWeight:"900",
        color:"#ffffff",
    }
})

export default styles;