import {StyleSheet} from "react-native";

const styles = StyleSheet.create({
    container:{
        flex:1,
        width:"100%",
        height:"100%",
        padding:10,
        
    },
    textOutBox:{
        fontSize:16,
        marginBottom:20,
    },
    box:{
        width:"100%",
        height:"70%",
        padding:10,
        borderWidth:2,
    },
    content:{
        width:"100%",
        height:50,
        flexDirection:"row",
        justifyContent:"space-between",
        marginVertical:5,
        alignItems:"center",
    },
    boxImageWithText:{
        width:90,
        height:25,
        flexDirection:"row",
    },
    boxImage:{
        width:30,
        height:25,
    },
    boxImageWith2Image:{
        width:55,
        height:25,
        flexDirection:"row",
        justifyContent:"space-around",
    },
    boxImageWith3Image:{
        width:80,
        height:25,
        flexDirection:"row",
        justifyContent:"space-around",
    },
    boxImageWithTextEmail:{
        width:200,
        height:25,
        flexDirection:"row",
        justifyContent:"space-around",
    },
    boxImageWithTextPassword:{
        width:90,
        height:25,
        flexDirection:"row",
        justifyContent:"space-around",
    },
    boxImageWithTextUsername:{
        width:130,
        height:25,
        flexDirection:"row",
        justifyContent:"space-around",
    },
    image:{
        height:25,
        width:25,
        resizeMode:"contain",
    },
    textContent:{
        fontSize:20,
        color:"#000000",

    },
    titleBox:{
        fontSize:25,
        color:"#000000",
    },
    editionButtonContainer:{
        width:"100%",
        height:100,
        justifyContent:"center",
        alignItems:"center",
    },
    editionButton:{
        width:200,
        height:"80%",
        justifyContent:"center",
        alignItems:"center",
        backgroundColor:"#8429AE",
        borderRadius:15,
        borderWidth:2,
    },
    textButton:{
        fontSize:25,
        fontWeight:"900",
        color:"#000000",
    }
})

export default styles;